# Generated by Django 4.1.2 on 2022-11-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=100, verbose_name='Name')),
                ('p', models.BooleanField(default=False, verbose_name='Premium')),
                ('an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='an', to='a.n', verbose_name='Active Note')),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ['-n'],
            },
        ),
    ]
